openapi: 3.0.0
info:
  title: AMC Docs
  version: 1.0.0
  description: The Documentation Server for the AMC platform
  contact:
    name: AYU DIGITAL LTD
    url: https://uat.bafut.co.uk
    email: s.banda911@googlemail.com

servers:
  - url: http://localhost:5000
    description: local server address

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /user:
    get:
      tags:
        - users
      summary: AMC USERSS
  /post:
    get:
      tags:
        - posts
      summary: AMC POSTS
  /clubs:
    get:
      tags:
        - clubs
      summary: AMC CLUBS
  /members:
    get:
      tags:
        - members
      summary: AMC MEMBERS
  /outputs:
    get:
      tags:
        - outputs
      summary: AMC OUTPUTS
